language: R
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "irc.irccloud.com#builds"
    nick: travisci
    password: Mangrove
